### ISSUE TITLE
Mail hatası

### ISSUE THREAD

**Issue by emircanturkyilmaz** [buraksarpkaya89/Python-shopping-CheckPrice#3]
Merhabalar,
Her şeyi ayarladıktan sonra şöyle bir hata alıyorum.
`Traceback (most recent call last):
  File "C:\Users\Evora\PycharmProjects\pythonProject\main.py", line 47, in <module>
    check_price()
  File "C:\Users\Evora\PycharmProjects\pythonProject\main.py", line 23, in check_price
    send_mail(title, content)
  File "C:\Users\Evora\PycharmProjects\pythonProject\main.py", line 37, in send_mail
    server.sendmail(sender, reciever, mailContent)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 875, in sendmail
    msg = _fix_eols(msg).encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 110: ordinal not in range(128)
`

**Comment by buraksarpkaya89** [comment]
Türkçe karakter kullandıysan onları değiştirmelisin

emircanturkyilmaz ***@***.***>, 10 May 2022 Sal, 12:01
tarihinde şunu yazdı:

**Comment by emircanturkyilmaz** [comment]
Halletim teşekkürler. :)
